In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/cadiyubu/Project_W7_CoffeeHealth/refs/heads/bibian/data/raw/salaries.csv")
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2024,MI,FT,Machine Learning Engineer,200200,USD,200200,US,0,US,M
1,2024,MI,FT,Machine Learning Engineer,186915,USD,186915,US,0,US,M
2,2024,MI,FT,Software Engineer,240240,USD,240240,US,0,US,M
3,2024,MI,FT,Software Engineer,221596,USD,221596,US,0,US,M
4,2024,SE,FT,Machine Learning Engineer,240240,USD,240240,US,0,US,M

In [3]:
#df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
#df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)

In [4]:
def df_info(df):
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    print("\n    ---- Statistics ---")
    return df.describe()
df_info(df)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29562 entries, 0 to 29561
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           29562 non-null  int64
 1   experience_level    29562 non-null  object
 2   employment_type     29562 non-null  object
 3   job_title           29562 non-null  object
 4   salary              29562 non-null  int64
 5   salary_currency     29562 non-null  object
 6   salary_in_usd       29562 non-null  int64
 7   employee_residence  29562 non-null  object
 8   remote_ratio        29562 non-null  int64
 9   company_location    29562 non-null  object
 10  company_size        29562 non-null  object
dtypes: int64(4), object(7)
memory usage: 2.5+ MB
None

    ---- Empty Values ---
work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

    ----- Dtypes -----
work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

    ---- Statistics ---

          work_year        salary  salary_in_usd  remote_ratio
count  29562.000000  2.956200e+04   29562.000000  29562.000000
mean    2023.567282  1.641725e+05  156262.504499     25.260470
std        0.657533  2.593987e+05   70767.667632     43.200518
min     2020.000000  1.400000e+04   15000.000000      0.000000
25%     2023.000000  1.065000e+05  106500.000000      0.000000
50%     2024.000000  1.463000e+05  146000.000000      0.000000
75%     2024.000000  1.980000e+05  196900.000000     50.000000
max     2024.000000  3.040000e+07  800000.000000    100.000000

In [5]:
region_map = {
    # North America
    'US': 'North_America', 'CA': 'North_America', 'MX': 'North_America',
    'PR': 'North_America', 'BS': 'North_America', 'HN': 'North_America',
    # Europe West
    'GB': 'Europe_West', 'DE': 'Europe_West', 'FR': 'Europe_West',
    'NL': 'Europe_West', 'IE': 'Europe_West', 'CH': 'Europe_West',
    'AT': 'Europe_West', 'BE': 'Europe_West', 'LU': 'Europe_West',
    'DK': 'Europe_West', 'SE': 'Europe_West', 'FI': 'Europe_West',
    'NO': 'Europe_West', 'PT': 'Europe_West', 'ES': 'Europe_West',
    'IT': 'Europe_West', 'GR': 'Europe_West', 'GI': 'Europe_West',
    # Europe East
    'PL': 'Europe_East', 'RO': 'Europe_East', 'CZ': 'Europe_East',
    'HU': 'Europe_East', 'SK': 'Europe_East', 'UA': 'Europe_East',
    'RS': 'Europe_East', 'HR': 'Europe_East', 'SI': 'Europe_East',
    'LT': 'Europe_East', 'LV': 'Europe_East', 'EE': 'Europe_East',
    'BA': 'Europe_East', 'MD': 'Europe_East', 'AD': 'Europe_East',
    # Asia Pacific
    'IN': 'Asia_Pacific', 'CN': 'Asia_Pacific', 'JP': 'Asia_Pacific',
    'KR': 'Asia_Pacific', 'SG': 'Asia_Pacific', 'AU': 'Asia_Pacific',
    'NZ': 'Asia_Pacific', 'HK': 'Asia_Pacific', 'TH': 'Asia_Pacific',
    'VN': 'Asia_Pacific', 'PH': 'Asia_Pacific', 'MY': 'Asia_Pacific',
    'ID': 'Asia_Pacific', 'PK': 'Asia_Pacific', 'IR': 'Asia_Pacific',
    # Middle East
    'AE': 'Middle_East', 'SA': 'Middle_East', 'QA': 'Middle_East',
    'IL': 'Middle_East', 'IQ': 'Middle_East', 'OM': 'Middle_East',
    'LB': 'Middle_East', 'AM': 'Middle_East',
    # Latin America
    'BR': 'Latin_America', 'AR': 'Latin_America', 'CL': 'Latin_America',
    'CO': 'Latin_America', 'VE': 'Latin_America', 'EC': 'Latin_America',
    # Africa
    'ZA': 'Africa', 'NG': 'Africa', 'KE': 'Africa', 'EG': 'Africa',
    'GH': 'Africa', 'DZ': 'Africa', 'CF': 'Africa', 'MU': 'Africa',
    # Other
    'MT': 'Other', 'AS': 'Other', 'RU': 'Other',
}

df['company_region'] = df['company_location'].map(region_map).fillna('Other')
df['residence_region'] = df['employee_residence'].map(region_map).fillna('Other')

Model 1 — predicts salary from company-related features (Diana).
Model 2 — predicts salary from experience level

We are going to study two models, Diana m1 and Bibian m2:


m1 = 'job_title','company_size', 'salary_currency','company_location','employee_residence'


m2 = 'job_title','employee_residence','experience_level', 'employment_type', 'salary_currency'

In [9]:
print("\nnumber of unique job titles ")
print(df.job_title.nunique())

print("\nnumber of unique employee residence region")
print(df.residence_region.nunique())

print("\nnumber of unique experience levels")
print(df.experience_level.nunique())

print("\nnumber of unique employment types")
print(df.employment_type.nunique())

number of unique job titles
196

number of unique employee residence region
8

number of unique experience levels
4

number of unique employment types
4

### Employee residence

In [10]:
df['residence_region'].value_counts()

residence_region
North_America    27484
Europe_West       1508
Asia_Pacific       228
Europe_East        121
Latin_America       82
Africa              71
Other               47
Middle_East         21
Name: count, dtype: int64

We are keeping only data where employee_residence > 100

In [ ]:
#residence_counts = df['employee_residence'].value_counts()

#more_than_100 = residence_counts[residence_counts >= 100].index

#df_f = df[df['employee_residence'].isin(more_than_100)].copy()

#display (df_f['employee_residence'].value_counts())
#display (df_f.shape)
#display (df.shape)

### job titles

In [11]:
df['job_title'].value_counts()

job_title
Data Scientist                   6450
Data Engineer                    5393
Data Analyst                     3813
Machine Learning Engineer        3209
Software Engineer                1513
                                 ...
Applied Research Scientist          1
CRM Data Analyst                    1
Big Data Developer                  1
Quantitative Research Analyst       1
Analytics Engineering Manager       1
Name: count, Length: 196, dtype: int64

In [14]:
title_counts = df['job_title'].value_counts()

more_than_1000_jobs = title_counts[title_counts >= 150].index

df_f = df[df['job_title'].isin(more_than_1000_jobs)].copy()

display (df_f['job_title'].value_counts())
display (df_f.shape)
display (df.shape)

job_title
Data Scientist                    6450
Data Engineer                     5393
Data Analyst                      3813
Machine Learning Engineer         3209
Software Engineer                 1513
Research Scientist                1319
Applied Scientist                  771
Data Architect                     725
Analytics Engineer                 654
Research Engineer                  600
Business Intelligence Engineer     374
Business Intelligence Analyst      329
Data Manager                       318
AI Engineer                        253
Research Analyst                   229
Business Intelligence              222
Machine Learning Scientist         206
Data Specialist                    164
Name: count, dtype: int64

(26542, 13)

(29562, 13)

In [18]:
X=df_f[['job_title','residence_region','experience_level', 'employment_type', 'salary_in_usd']]
X.head()

,job_title,residence_region,experience_level,employment_type,salary_in_usd
0,Machine Learning Engineer,North_America,MI,FT,200200
1,Machine Learning Engineer,North_America,MI,FT,186915
2,Software Engineer,North_America,MI,FT,240240
3,Software Engineer,North_America,MI,FT,221596
4,Machine Learning Engineer,North_America,SE,FT,240240

In [ ]:
# X.to_csv('m2_model_clean.csv', sep=',', index=False)

### salary by country

In [19]:
import scipy.stats as stats

group1 = X[X['residence_region'] == 'North_America']['salary_in_usd']
group2 = X[X['residence_region'] == 'Europe_West']['salary_in_usd']
group3 = X[X['residence_region'] == 'Asia_Pacific']['salary_in_usd']
group4 = X[X['residence_region'] == 'Europe_East']['salary_in_usd']
group5 = X[X['residence_region'] == 'Latin_America ']['salary_in_usd']

# ANOVA
f_stat, p_value = stats.f_oneway(group1, group2, group3, group4, group5)


print(f"Estadístico F: {f_stat:.4f}")
print(f"P-Value: {p_value:.16f}")

Estadístico F: nan
P-Value: nan

C:\Users\fotos\AppData\Local\Temp\ipykernel_16516\1236813768.py:10: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  f_stat, p_value = stats.f_oneway(group1, group2, group3, group4, group5)

### salary by job title

In [25]:
datas_group_job = X[X['job_title'] == 'Data Scientist']['salary_in_usd']
datae_group_job = X[X['job_title'] == 'Data Engineer']['salary_in_usd']
dataa_group_job = X[X['job_title'] == 'Data Analyst']['salary_in_usd']
datam_group_job = X[X['job_title'] == 'Machine Learning Engineer']['salary_in_usd']

# ANOVA one way
f_stat, p_value = stats.f_oneway(datas_group_job, datae_group_job, dataa_group_job, datam_group_job)


print(f"Estadístico F: {f_stat:.4f}")
print(f"P-Value: {p_value:.16f}")

Estadístico F: 1230.5721
P-Value: 0.0000000000000000

### salary by experience level

In [23]:
exp_en_group_exp = df_f[df_f['experience_level'] == 'EN']['salary_in_usd']
exp_ex_group_exp = df_f[df_f['experience_level'] == 'EX']['salary_in_usd']
exp_mi_group_exp = df_f[df_f['experience_level'] == 'MI']['salary_in_usd']
exp_se_group_exp = df_f[df_f['experience_level'] == 'SE']['salary_in_usd']

# ANOVA
f_stat, p_value = stats.f_oneway(exp_en_group_exp, exp_ex_group_exp, exp_mi_group_exp, exp_se_group_exp)


print(f"Estadístico F: {f_stat:.4f}")
print(f"P-Value: {p_value:.16f}")

Estadístico F: 928.3411
P-Value: 0.0000000000000000

In [21]:
from scipy.stats import f_oneway

In [22]:
cat_cols = X.select_dtypes(include="object").columns

results = {
    col: f_oneway(*X.groupby(col)["salary_in_usd"].apply(list))
    for col in cat_cols
}

[print(f"{col:25} F={f:8.1f}  p={p:.2e}") for col, (f, p) in results.items()]

job_title                 F=   324.8  p=0.00e+00
residence_region          F=   299.7  p=0.00e+00
experience_level          F=   928.3  p=0.00e+00
employment_type           F=    18.8  p=3.59e-12

[None, None, None, None]

In [ ]:
#H0 rejected

In [26]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd

tukey = pairwise_tukeyhsd(endog=df_f['salary_in_usd'],
                          groups=df_f['employee_residence'],
                          alpha=0.05)
print(tukey)

D:\Anaconda\Lib\site-packages\scipy\integrate\_quadpack_py.py:1264: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  quad_r = quad(f, low, high, args=args, full_output=self.full_output,

       Multiple Comparison of Means - Tukey HSD, FWER=0.05
=================================================================
group1 group2   meandiff   p-adj     lower        upper    reject
-----------------------------------------------------------------
    AD     AE   40921.6667    1.0 -283190.9948 365034.3281  False
    AD     AM  -19856.3333    1.0 -343968.9948 304256.3281  False
    AD     AR     29738.25    1.0 -256739.5759 316216.0759  False
    AD     AT      14258.6    1.0 -280131.3442 308648.5442  False
    AD     AU   81475.4531    1.0 -201398.7347  364349.641  False
    AD     BE     26119.75    1.0  -287700.985  339940.485  False
    AD     BG      29255.0    1.0 -367700.3198 426210.3198  False
    AD     BR     13613.75    1.0 -272864.0759 300091.5759  False
    AD     CA   91567.8869    1.0  -189315.424 372451.1978  False
    AD     CF      -1529.0    1.0 -345302.3911 342244.3911  False
    AD     CH      86442.5    1.0 -211273.9899 384158.9899  False
    AD     CL      19946.5    1.0  -293874.235  333767.235  False
    AD     CN      74659.0    1.0 -322296.3198 471614.3198  False
    AD     CO   25311.2667    1.0 -264583.9107  315206.444  False
    AD     CR     -30745.0    1.0 -427700.3198 366210.3198  False
    AD     CY      12956.0    1.0 -383999.3198 409911.3198  False
    AD     CZ       9254.5    1.0 -334518.8911 353027.8911  False
    AD     DE   67239.5444    1.0 -215005.3341  349484.423  False
    AD     DO      59255.0    1.0 -337700.3198 456210.3198  False
    AD     DZ      49255.0    1.0 -347700.3198 446210.3198  False
    AD     EC     -34745.0    1.0 -431700.3198 362210.3198  False
    AD     EE      -5561.0    1.0 -299950.9442 288828.9442  False
    AD     EG   94925.5882    1.0 -193901.8316 383753.0081  False
    AD     ES    8432.0547    1.0 -273352.0551 290216.1645  False
    AD     FI      35640.6    1.0 -271839.6686 343120.8686  False
    AD     FR   44891.8986    1.0 -237824.5674 327608.3645  False
    AD     GB   38564.6699    1.0 -242296.6469 319425.9868  False
    AD     GR     826.8571    1.0  -289714.687 291368.4013  False
    AD     HK      14795.0    1.0 -328978.3911 358568.3911  False
    AD     HR      15549.5    1.0  -298271.235  329370.235  False
    AD     HU  -18605.3333    1.0 -342717.9948 305507.3281  False
    AD     ID     -35745.0    1.0 -432700.3198 361210.3198  False
    AD     IE   45291.4737    1.0 -242690.1832 333273.1306  False
    AD     IL   71619.3333    1.0 -252493.3281 395731.9948  False
    AD     IN   -6248.1875    1.0 -289846.7662 277350.3912  False
    AD     IR      49255.0    1.0 -347700.3198 446210.3198  False
    AD     IT   24406.3889    1.0 -263974.9651 312787.7429  False
    AD     JE      49255.0    1.0 -347700.3198 446210.3198  False
    AD     JP    45076.625    1.0 -252639.8649 342793.1149  False
    AD     KE     -15745.0    1.0 -359518.3911 328028.3911  False
    AD     KR      45607.0    1.0 -298166.3911 389380.3911  False
    AD     KW       -745.0    1.0 -397700.3198 396210.3198  False
    AD     LT   12575.5769    1.0 -273461.1744 298612.3282  False
    AD     LU       4810.0    1.0 -392145.3198 401765.3198  False
    AD     LV    6314.6875    1.0 -283013.7343 295643.1093  False
    AD     MT      11878.0    1.0 -312234.6614 335990.6614  False
    AD     MX      99505.6    1.0 -190389.5773 389400.7773  False
    AD     NG     -11745.0    1.0  -325565.735  302075.735  False
    AD     NL   22956.9773    1.0  -260904.558 306818.5126  False
    AD     NO      37717.0    1.0 -306056.3911 381490.3911  False
    AD     NZ      74417.6    1.0 -219972.3442 368807.5442  False
    AD     OM      -3897.0    1.0 -400852.3198 393058.3198  False
    AD     PE     -23745.0    1.0 -420700.3198 373210.3198  False
    AD     PH      -5904.2    1.0 -300294.1442 288485.7442  False
    AD     PK      -7006.0    1.0 -331118.6614 317106.6614  False
    AD     PL   31133.5385    1.0 -260152.0314 322419.1083  False
    AD     PR     116755.0    1.0  -197065.735  430575.735  False
    AD     PT   11485.0435    1.0 -275241.7854 298211.8724  False
    AD     QA     249255.0 0.9747 -147700.3198 646210.3198  False
    AD     RO      -6407.0    1.0 -313887.2686 301073.2686  False
    AD     RS   -8234.3333    1.0 -332346.9948 315878.3281  False
    AD     RU    -926.6667    1.0 -325039.3281 323185.9948  False
    AD     SG      41413.0    1.0 -302360.3911 385186.3911  False
    AD     SI      -3889.2    1.0 -311369.4686 303591.0686  False
    AD     TH     -23788.0    1.0 -367561.3911 319985.3911  False
    AD     TR   -4716.0714    1.0 -295257.6156 285825.4728  False
    AD     UA   62810.5556    1.0 -233062.4708 358683.5819  False
    AD     UG     -14745.0    1.0 -411700.3198 382210.3198  False
    AD     US  112735.3762    1.0 -167960.2389 393430.9913  False
    AD     UZ      31255.0    1.0 -292857.6614 355367.6614  False
    AD     VN      12255.0    1.0  -301565.735  326075.735  False
    AD     ZA      13464.5    1.0 -272572.2513 299501.2513  False
    AE     AM     -60778.0    1.0 -289960.2608 168404.2608  False
    AE     AR  -11183.4167    1.0 -183070.1122 160703.2789  False
    AE     AT  -26663.0667    1.0 -211435.7124 158109.5791  False
    AE     AU   40553.7865    1.0  -125257.243 206364.8159  False
    AE     BE  -14801.9167    1.0 -229182.2914 199578.4581  False
    AE     BG  -11666.6667    1.0 -335779.3281 312445.9948  False
    AE     BR  -27307.9167    1.0 -199194.6122 144578.7789  False
    AE     CA   50646.2202    1.0 -111745.0533 213037.4938  False
    AE     CF  -42450.6667    1.0 -298684.2238 213782.8905  False
    AE     CH   45520.8333    1.0 -144507.0586 235548.7252  False
    AE     CL  -20975.1667    1.0 -235355.5414 193405.2081  False
    AE     CN   33737.3333    1.0 -290375.3281 357849.9948  False
    AE     CO     -15610.4    1.0 -193134.2158 161913.4158  False
    AE     CR  -71666.6667    1.0 -395779.3281 252445.9948  False
    AE     CY  -27965.6667    1.0 -352078.3281 296146.9948  False
    AE     CZ  -31667.1667    1.0 -287900.7238 224566.3905  False
    AE     DE   26317.8778    1.0 -138417.2514  191053.007  False
    AE     DO   18333.3333    1.0 -305779.3281 342445.9948  False
    AE     DZ    8333.3333    1.0 -315779.3281 332445.9948  False
    AE     EC  -75666.6667    1.0 -399779.3281 248445.9948  False
    AE     EE  -46482.6667    1.0 -231255.3124 138289.9791  False
    AE     EG   54003.9216    1.0 -121770.8485 229778.6916  False
    AE     ES   -32489.612    1.0 -196434.0413 131454.8174  False
    AE     FI   -5281.0667    1.0 -210267.9124 199705.7791  False
    AE     FR    3970.2319    1.0   -161571.58 169512.0437  False
    AE     GB   -2356.9967    1.0 -164710.2248 159996.2313  False
    AE     GR  -40094.8095    1.0 -218672.1884 138482.5694  False
    AE     HK  -26126.6667    1.0 -282360.2238 230106.8905  False
    AE     HR  -25372.1667    1.0 -239752.5414 189008.2081  False
    AE     HU     -59527.0    1.0 -288709.2608 169655.2608  False
    AE     ID  -76666.6667    1.0 -400779.3281 247445.9948  False
    AE     IE     4369.807    1.0 -170011.7461 178751.3601  False
    AE     IL   30697.6667    1.0 -198484.5941 259879.9274  False
    AE     IN  -47169.8542    1.0 -214213.6964  119873.988  False
    AE     IR    8333.3333    1.0 -315779.3281 332445.9948  False
    AE     IT  -16515.2778    1.0 -191556.1208 158525.5652  False
    AE     JE    8333.3333    1.0 -315779.3281 332445.9948  False
    AE     JP    4154.9583    1.0 -185872.9336 194182.8502  False
    AE     KE  -56666.6667    1.0 -312900.2238 199566.8905  False
    AE     KR    4685.3333    1.0 -251548.2238 260918.8905  False
    AE     KW  -41666.6667    1.0 -365779.3281 282445.9948  False
    AE     LT  -28346.0897    1.0 -199496.6505  142804.471  False
    AE     LU  -36111.6667    1.0 -360224.3281 288000.9948  False
    AE     LV  -34606.9792    1.0 -211203.7713  141989.813  False
    AE     MT  -29043.6667    1.0 -258225.9274 200138.5941  False
    AE     MX   58583.9333    1.0 -118939.8825 236107.7492  False
    AE     NG  -52666.6667    1.0 -267047.0414 161713.7081  False
    AE     NL  -17964.6894    1.0 -185454.5774 149525.1986  False
    AE     NO   -3204.6667    1.0 -259438.2238 253028.8905  False
    AE     NZ   33495.9333    1.0 -151276.7124 218268.5791  False
    AE     OM  -44818.6667    1.0 -368931.3281 279293.9948  False
    AE     PE  -64666.6667    1.0 -388779.3281 259445.9948  False
    AE     PH  -46825.8667    1.0 -231598.5124 137946.7791  False
    AE     PK  -47927.6667    1.0 -277109.9274 181254.5941  False
    AE     PL   -9788.1282    1.0 -189573.4851 169997.2287  False
    AE     PR   75833.3333    1.0 -138547.0414 290213.7081  False
    AE     PT  -29436.6232    1.0 -201738.0038 142864.7574  False
    AE     QA  208333.3333 0.9614 -115779.3281 532445.9948  False
    AE     RO  -47328.6667    1.0 -252315.5124 157658.1791  False
    AE     RS     -49156.0    1.0 -278338.2608 180026.2608  False
    AE     RU  -41848.3333    1.0 -271030.5941 187333.9274  False
    AE     SG     491.3333    1.0 -255742.2238 256724.8905  False
    AE     SI  -44810.8667    1.0 -249797.7124 160175.9791  False
    AE     TH  -64709.6667    1.0 -320943.2238 191523.8905  False
    AE     TR  -45637.7381    1.0  -224215.117 132939.6408  False
    AE     UA   21888.8889    1.0 -165237.6434 209015.4212  False
    AE     UG  -55666.6667    1.0 -379779.3281 268445.9948  False
    AE     US   71813.7096    1.0  -90252.6956 233880.1148  False
    AE     UZ   -9666.6667    1.0 -238848.9274 219515.5941  False
    AE     VN  -28666.6667    1.0 -243047.0414 185713.7081  False
    AE     ZA  -27457.1667    1.0 -198607.7274 143693.3941  False
    AM     AR   49594.5833    1.0 -122292.1122 221481.2789  False
    AM     AT   34114.9333    1.0 -150657.7124 218887.5791  False
    AM     AU  101331.7865 0.9851   -64479.243 267142.8159  False
    AM     BE   45976.0833    1.0 -168404.2914 260356.4581  False
    AM     BG   49111.3333    1.0 -275001.3281 373223.9948  False
    AM     BR   33470.0833    1.0 -138416.6122 205356.7789  False
    AM     CA  111424.2202 0.8938  -50967.0533 273815.4938  False
    AM     CF   18327.3333    1.0 -237906.2238 274560.8905  False
    AM     CH  106298.8333  0.998  -83729.0586 296326.7252  False
    AM     CL   39802.8333    1.0 -174577.5414 254183.2081  False
    AM     CN   94515.3333    1.0 -229597.3281 418627.9948  False
    AM     CO      45167.6    1.0 -132356.2158 222691.4158  False
    AM     CR  -10888.6667    1.0 -335001.3281 313223.9948  False
    AM     CY   32812.3333    1.0 -291300.3281 356924.9948  False
    AM     CZ   29110.8333    1.0 -227122.7238 285344.3905  False
    AM     DE   87095.8778 0.9996  -77639.2514  251831.007  False
    AM     DO   79111.3333    1.0 -245001.3281 403223.9948  False
    AM     DZ   69111.3333    1.0 -255001.3281 393223.9948  False
    AM     EC  -14888.6667    1.0 -339001.3281 309223.9948  False
    AM     EE   14295.3333    1.0 -170477.3124 199067.9791  False
    AM     EG  114781.9216 0.9496  -60992.8485 290556.6916  False
    AM     ES    28288.388    1.0 -135656.0413 192232.8174  False
    AM     FI   55496.9333    1.0 -149489.9124 260483.7791  False
    AM     FR   64748.2319    1.0   -100793.58 230290.0437  False
    AM     GB   58421.0033    1.0 -103932.2248 220774.2313  False
    AM     GR   20683.1905    1.0 -157894.1884 199260.5694  False
    AM     HK   34651.3333    1.0 -221582.2238 290884.8905  False
    AM     HR   35405.8333    1.0 -178974.5414 249786.2081  False
    AM     HU       1251.0    1.0 -227931.2608 230433.2608  False
    AM     ID  -15888.6667    1.0 -340001.3281 308223.9948  False
    AM     IE    65147.807    1.0 -109233.7461 239529.3601  False
    AM     IL   91475.6667    1.0 -137706.5941 320657.9274  False
    AM     IN   13608.1458    1.0 -153435.6964  180651.988  False
    AM     IR   69111.3333    1.0 -255001.3281 393223.9948  False
    AM     IT   44262.7222    1.0 -130778.1208 219303.5652  False
    AM     JE   69111.3333    1.0 -255001.3281 393223.9948  False
    AM     JP   64932.9583    1.0 -125094.9336 254960.8502  False
    AM     KE    4111.3333    1.0 -252122.2238 260344.8905  False
    AM     KR   65463.3333    1.0 -190770.2238 321696.8905  False
    AM     KW   19111.3333    1.0 -305001.3281 343223.9948  False
    AM     LT   32431.9103    1.0 -138718.6505  203582.471  False
    AM     LU   24666.3333    1.0 -299446.3281 348778.9948  False
    AM     LV   26171.0208    1.0 -150425.7713  202767.813  False
    AM     MT   31734.3333    1.0 -197447.9274 260916.5941  False
    AM     MX  119361.9333 0.9204  -58161.8825 296885.7492  False
    AM     NG    8111.3333    1.0 -206269.0414 222491.7081  False
    AM     NL   42813.3106    1.0 -124676.5774 210303.1986  False
    AM     NO   57573.3333    1.0 -198660.2238 313806.8905  False
    AM     NZ   94273.9333 0.9999  -90498.7124 279046.5791  False
    AM     OM   15959.3333    1.0 -308153.3281 340071.9948  False
    AM     PE   -3888.6667    1.0 -328001.3281 320223.9948  False
    AM     PH   13952.1333    1.0 -170820.5124 198724.7791  False
    AM     PK   12850.3333    1.0 -216331.9274 242032.5941  False
    AM     PL   50989.8718    1.0 -128795.4851 230775.2287  False
    AM     PR  136611.3333 0.9669  -77769.0414 350991.7081  False
    AM     PT   31341.3768    1.0 -140960.0038 203642.7574  False
    AM     QA  269111.3333 0.4042  -55001.3281 593223.9948  False
    AM     RO   13449.3333    1.0 -191537.5124 218436.1791  False
    AM     RS      11622.0    1.0 -217560.2608 240804.2608  False
    AM     RU   18929.6667    1.0 -210252.5941 248111.9274  False
    AM     SG   61269.3333    1.0 -194964.2238 317502.8905  False
    AM     SI   15967.1333    1.0 -189019.7124 220953.9791  False
    AM     TH   -3931.6667    1.0 -260165.2238 252301.8905  False
    AM     TR   15140.2619    1.0  -163437.117 193717.6408  False
    AM     UA   82666.8889    1.0 -104459.6434 269793.4212  False
    AM     UG    5111.3333    1.0 -319001.3281 329223.9948  False
    AM     US  132591.7096 0.4486  -29474.6956 294658.1148  False
    AM     UZ   51111.3333    1.0 -178070.9274 280293.5941  False
    AM     VN   32111.3333    1.0 -182269.0414 246491.7081  False
    AM     ZA   33320.8333    1.0 -137829.7274 204471.3941  False
    AR     AT    -15479.65    1.0 -121127.4521  90168.1521  False
    AR     AU   51737.2031 0.6327  -15447.8024 118922.2086  False
    AR     BE      -3618.5    1.0 -155208.3167 147971.3167  False
    AR     BG      -483.25    1.0 -286961.0759 285994.5759  False
    AR     BR     -16124.5    1.0  -97152.6654  64903.6654  False
    AR     CA   61829.6369 0.0183    3593.4524 120065.8214   True
    AR     CF    -31267.25    1.0 -237849.3481 175314.8481  False
    AR     CH     56704.25 0.9999  -57886.8804 171295.3804  False
    AR     CL     -9791.75    1.0 -161381.5667 141798.0667  False
    AR     CN     44920.75    1.0 -241557.0759 331398.5759  False
    AR     CO   -4426.9833    1.0  -96813.3062  87959.3395  False
    AR     CR    -60483.25    1.0 -346961.0759 225994.5759  False
    AR     CY    -16782.25    1.0 -303260.0759 269695.5759  False
    AR     CZ    -20483.75    1.0 -227065.8481 186098.3481  False
    AR     DE   37501.2944 0.9949  -26982.7367 101985.3256  False
    AR     DO     29516.75    1.0 -256961.0759 315994.5759  False
    AR     DZ     19516.75    1.0 -266961.0759 305994.5759  False
    AR     EC    -64483.25    1.0 -350961.0759 221994.5759  False
    AR     EE    -35299.25    1.0 -140947.0521  70348.5521  False
    AR     EG   65187.3382  0.767  -23791.8574 154166.5339  False
    AR     ES  -21306.1953    1.0    -83742.59  41130.1993  False
    AR     FI      5902.35    1.0 -132083.6434 143888.3434  False
    AR     FR   15153.6486    1.0  -51364.1606  81671.4577  False
    AR     GB    8826.4199    1.0  -49303.5906  66956.4305  False
    AR     GR  -28911.3929    1.0 -123306.3488  65483.5631  False
    AR     HK    -14943.25    1.0 -221525.3481 191638.8481  False
    AR     HR    -14188.75    1.0 -165778.5667 137401.0667  False
    AR     HU  -48343.5833    1.0 -220230.2789 123543.1122  False
    AR     ID    -65483.25    1.0 -351961.0759 220994.5759  False
    AR     IE   15553.2237    1.0  -70641.0541 101747.5015  False
    AR     IL   41881.0833    1.0 -130005.6122 213767.7789  False
    AR     IN  -35986.4375 0.9998 -106158.8871  34186.0121  False
    AR     IR     19516.75    1.0 -266961.0759 305994.5759  False
    AR     IT   -5331.8611    1.0  -92852.2826  82188.5604  False
    AR     JE     19516.75    1.0 -266961.0759 305994.5759  False
    AR     JP    15338.375    1.0  -99252.7554 129929.5054  False
    AR     KE    -45483.25    1.0 -252065.3481 161098.8481  False
    AR     KR     15868.75    1.0 -190713.3481 222450.8481  False
    AR     KW    -30483.25    1.0 -316961.0759 255994.5759  False
    AR     LT  -17162.6731    1.0  -96617.3262  62291.9801  False
    AR     LU    -24928.25    1.0 -311406.0759 261549.5759  False
    AR     LV  -23423.5625    1.0 -114015.8054  67168.6804  False
    AR     MT    -17860.25    1.0 -189746.9456 154026.4456  False
    AR     MX     69767.35 0.6884  -22618.9729 162153.6729  False
    AR     NG    -41483.25    1.0 -193073.0667 110106.5667  False
    AR     NL   -6781.2727    1.0  -78009.0064  64446.4609  False
    AR     NO      7978.75    1.0 -198603.3481 214560.8481  False
    AR     NZ     44679.35    1.0  -60968.4521 150327.1521  False
    AR     OM    -33635.25    1.0 -320113.0759 252842.5759  False
    AR     PE    -53483.25    1.0 -339961.0759 232994.5759  False
    AR     PH    -35642.45    1.0 -141290.2521  70005.3521  False
    AR     PK    -36744.25    1.0 -208630.9456 135142.4456  False
    AR     PL    1395.2885    1.0  -95265.4689  98056.0458  False
    AR     PR     87016.75 0.9963  -64573.0667 238606.5667  False
    AR     PT  -18253.2065    1.0 -100157.3775  63650.9645  False
    AR     QA    219516.75 0.6472  -66961.0759 505994.5759  False
    AR     RO    -36145.25    1.0 -174131.2434 101840.7434  False
    AR     RS  -37972.5833    1.0 -209859.2789 133914.1122  False
    AR     RU  -30664.9167    1.0 -202551.6122 141221.7789  False
    AR     SG     11674.75    1.0 -194907.3481 218256.8481  False
    AR     SI    -33627.45    1.0 -171613.4434 104358.5434  False
    AR     TH    -53526.25    1.0 -260108.3481 153055.8481  False
    AR     TR  -34454.3214    1.0 -128849.2774  59940.6346  False
    AR     UA   33072.3056    1.0   -76640.349 142784.9601  False
    AR     UG    -44483.25    1.0 -330961.0759 241994.5759  False
    AR     US   82997.1262    0.0   25673.0723 140321.1802   True
    AR     UZ      1516.75    1.0 -170369.9456 173403.4456  False
    AR     VN    -17483.25    1.0 -169073.0667 134106.5667  False
    AR     ZA    -16273.75    1.0  -95728.4031  63180.9031  False
    AT     AU   67216.8531 0.8509  -28227.9973 162661.7035  False
    AT     BE     11861.15    1.0 -154197.1742 177919.4742  False
    AT     BG      14996.4    1.0 -279393.5442 309386.3442  False
    AT     BR      -644.85    1.0 -106292.6521 105002.9521  False
    AT     CA   77309.2869 0.2893  -12062.6757 166681.2495  False
    AT     CF     -15787.6    1.0  -233208.983  201633.783  False
    AT     CH      72183.9 0.9991  -60958.9619 205326.7619  False
    AT     CL       5687.9    1.0 -160370.4242 171746.2242  False
    AT     CN      60400.4    1.0 -233989.5442 354790.3442  False
    AT     CO   11052.6667    1.0 -103538.4637  125643.797  False
    AT     CR     -45003.6    1.0 -339393.5442 249386.3442  False
    AT     CY      -1302.6    1.0 -295692.5442 293087.3442  False
    AT     CZ      -5004.1    1.0  -222425.483  212417.283  False
    AT     DE   52980.9444 0.9973  -40582.3217 146544.2106  False
    AT     DO      44996.4    1.0 -249393.5442 339386.3442  False
    AT     DZ      34996.4    1.0 -259393.5442 329386.3442  False
    AT     EC     -49003.6    1.0 -343393.5442 245386.3442  False

In [27]:
# cual es el mejor conjunto de columnas para el modelo que elijamos

### train test

In [28]:
#extracting features

In [29]:
def features_target_extract(df, drop_cols, target_col):
    df_model = df.drop(columns=drop_cols, errors='ignore')
    cols = df_model.columns
    target = df_model[target_col] if target_col in cols else None
    if target is None: print('No target column; returning features only')
    features = df_model.drop(columns=[c for c in [target_col] if c in cols])
    return df_model, features, target

In [30]:
X, features, target = features_target_extract(X, [], 'salary_in_usd')

In [31]:
display(X.head())
display(features.head())
display(target)

,job_title,residence_region,experience_level,employment_type,salary_in_usd
0,Machine Learning Engineer,North_America,MI,FT,200200
1,Machine Learning Engineer,North_America,MI,FT,186915
2,Software Engineer,North_America,MI,FT,240240
3,Software Engineer,North_America,MI,FT,221596
4,Machine Learning Engineer,North_America,SE,FT,240240

                   job_title residence_region experience_level employment_type
0  Machine Learning Engineer    North_America               MI              FT
1  Machine Learning Engineer    North_America               MI              FT
2          Software Engineer    North_America               MI              FT
3          Software Engineer    North_America               MI              FT
4  Machine Learning Engineer    North_America               SE              FT

0        200200
1        186915
2        240240
3        221596
4        240240
          ...
29555     28369
29556    165000
29557    412000
29559    105000
29561     94665
Name: salary_in_usd, Length: 26542, dtype: int64

### train test split

In [ ]:
X_train,X_test, y_train,y_test = train_test_split(features,target,test_size=0.2,random_state=0)
X_train.head()

In [ ]:
# dummies for job_title	employee_residence	experience_level	employment_type

In [ ]:
# from sklearn.preprocessing import OneHotEncoder

In [ ]:
nonnum_cols = ['job_title','employee_residence','experience_level', 'employment_type']

In [ ]:
X_train = pd.get_dummies(X_train, columns=nonnum_cols, drop_first=True)
X_test  = pd.get_dummies(X_test,  columns=nonnum_cols, drop_first=True)

X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
X_test_scaled  = pd.DataFrame(scaler.transform(X_test),      columns=X_test.columns,  index=X_test.index)

In [ ]:
X_train.shape

## Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_scaled, y_train)

#evaluation
score_train = model.score(X_train_scaled, y_train)
score_test  = model.score(X_test_scaled,  y_test)

print(f"R² train: {score_train:.3f}")
print(f"R² test:  {score_test:.3f}")

## KNN

In [ ]:
# X_train_scaled 
# X_test_scaled

In [ ]:
def knn_modelling(train_df, test_df, y_train, y_test):
    knn = KNeighborsRegressor()
    knn.fit(train_df, y_train)
    return f"The R2 of the model is {knn.score(test_df, y_test):.2f}"

from sklearn.neighbors import KNeighborsRegressor

def knn_modelling(train_df, test_df, y_train, y_test):
    knn = KNeighborsRegressor()
    
    knn.fit(train_df, y_train)
    
    score_train = knn.score(train_df, y_train)
    score_test = knn.score(test_df, y_test)
    
    return f"R² train: {score_train:.3f}\nR² test: {score_test:.3f}"

In [ ]:
knn_results = knn_modelling(X_train_scaled, X_test_scaled, y_train, y_test)
print(knn_results)

## Bagging Regressor - Random Forests

In [ ]:
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error

#paremetrics

PARAMS = {
    'n_estimators': 100,
    'max_depth': 20,
    'random_state': 42
}

# training
model = BaggingRegressor(RandomForestRegressor(**PARAMS))
model.fit(X_train_scaled, y_train)

# predictions and metrics

y_pred = model.predict(X_test_scaled)

print(f"R2 Score: {model.score(X_test_scaled, y_test):.4f}")
print(f"MAE:      {mean_absolute_error(y_test, y_pred):.2f}")
print(f"MSE:      {mean_squared_error(y_test, y_pred):.2f}")
print(f"RMSE:     {root_mean_squared_error(y_test, y_pred):.2f}")

### Random forest

In [ ]:
PARAMS = {
    'n_estimators': 100,
    'max_depth': 20,
    'random_state': 42
}

model = RandomForestRegressor(**PARAMS)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(f"R2 Score: {model.score(X_test_scaled, y_test):.4f}")
print(f"MAE:      {mean_absolute_error(y_test, y_pred):.2f}")
print(f"MSE:      {mean_squared_error(y_test, y_pred):.2f}")
print(f"RMSE:     {root_mean_squared_error(y_test, y_pred):.2f}")